name: replace-repo-topics
author: gendloop
description: 'Replace all repository topics'
inputs:
# Required
  repo:
    description: 'Repo Name (e.g. MyRepo)'
    required: true
    default: ''
  topics:
    description: 'Topics (e.g. "t1","t2")'
    required: true
    default: ''

# Optional
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}
  user:
    description: 'User Name'
    required: false
    default: ${{ github.actor }}

runs:
  using: 'composite'
  steps:
    - name: replace-repo-topics
      shell: bash
      run: |
        curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.user }}/${{ inputs.repo }}/topics \
          -d '${"names":[${{ inputs.github.topics }}]}'
